[package]
name = "plotrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-unit = "4.0.17"
plotly = { version = "0.8.3", features = ["kaleido"]}
tempfile = "3.3.0"
